name: daily_expense_tracker
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  hive_flutter: ^1.1.0
  intl: ^0.20.2
  path_provider: ^2.1.5
  cupertino_icons: ^1.0.8
  rxdart: ^0.28.0
  hive: ^2.2.3
  flex_color_scheme: ^8.2.0
  google_fonts: ^6.3.0
  flutter_animate: ^4.5.2
  local_auth: ^2.3.0
  crypto: ^3.0.6
  share_plus: ^11.1.0
  file_picker: ^10.3.1
  pdf: ^3.11.3
  printing: ^5.14.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.5.4
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true

  fonts:
    - family: NotoNaskhArabic
      fonts:
        - asset: assets/fonts/NotoNaskhArabic-Regular.ttf
        - asset: assets/fonts/NotoNaskhArabic-Bold.ttf
          weight: 700
